code --install-extension batisteo.vscode-django
code --install-extension bracketpaircolordlw.bracket-pair-color-dlw
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension chakrounanas.turbo-console-log
code --install-extension chamboug.js-auto-backticks
code --install-extension christian-kohler.npm-intellisense
code --install-extension danielknights.logger
code --install-extension dbaeumer.vscode-eslint
code --install-extension devsense.composer-php-vscode
code --install-extension devsense.intelli-php-vscode
code --install-extension devsense.phptools-vscode
code --install-extension devsense.profiler-php-vscode
code --install-extension dracula-theme.theme-dracula
code --install-extension drcika.apc-extension
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension heybourn.headwind
code --install-extension humao.rest-client
code --install-extension icrawl.discord-vscode
code --install-extension irongeek.vscode-env
code --install-extension kamikillerto.vscode-colorize
code --install-extension kevinrose.vsc-python-indent
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension pkief.material-icon-theme
code --install-extension prisma.prisma
code --install-extension pulkitgangwar.nextjs-snippets
code --install-extension redhat.vscode-xml
code --install-extension ritwickdey.liveserver
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension wallabyjs.console-ninja
code --install-extension willluke.nextjs
code --install-extension willstakayama.vscode-nextjs-snippets
code --install-extension wix.vscode-import-cost
